apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: test
  
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: test
  type: LoadBalancer

---
apiVersion: v1
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: db-configmap 
data:
  # Configuration values can be set as key-value properties
  database: mongodb
  database_uri: mongodb://env-configmap:27017
  
  # Or set as complete file contents (even JSON!)
  keys: | 
    image.public.key=771 
    rsa.public.key=42



---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
  
spec:  
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - image: gcr.io/kmsh-250102/kaniko-push
          imagePullPolicy: Always
          name: test
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: configmap-volume
            mountPath: /etc/config
      volumes:
      - name: configmap-volume
        configMap:
            name: db-configmap
