
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pearson-deployment
spec:
  selector:
    matchLabels:
      app: pearson
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: pearson
    spec:
      containers:
      - name: pearson
        image: gcr.io/concise-haven-327611/next-app:00
        ports:
        - containerPort: 8080
