
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Rnow-deployment
spec:
  selector:
    matchLabels:
      app: Rnow
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: Rnow
    spec:
      containers:
      - name: Rnow
        image: gcr.io/concise-haven-327611/Rnow-app:00
        ports:
        - containerPort: 8080
